# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Do not keep secrets in the repository,
# instead read values from the environment.

# export SECRET_KEY_BASE_DEV=$(grep -A1 'development:' config/secrets_internal.yml | tail -n1); SECRET_KEY_BASE_DEV=${SECRET_KEY_BASE_DEV//*secret_key_base: /}
development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

# export SECRET_KEY_BASE_TEST=$(grep -A1 'test:' config/secrets_internal.yml | tail -n1); SECRET_KEY_BASE_TEST=${SECRET_KEY_BASE_TEST//*secret_key_base: /}
test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
